import { useEffect, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { ArrowLeft, ArrowUpRight, Search } from 'lucide-react'
const modules = import.meta.glob('../docs/*.md', { query: '?raw', import: 'default' })
const pages = [ ['getting-started','Getting started'], ['features','What Cider can do'], ['tasks','Tasks & linked work'], ['notes','Notes & folders'], ['agents','Your agents'], ['notch','The notch'], ['usage','Usage & limits'], ['cli','Cider commands'] ]
export function Docs({slug}: {slug:string}) {
 const [markdown,setMarkdown]=useState('');const [loading,setLoading]=useState(true);const [query,setQuery]=useState('')
 useEffect(()=>{ let active=true;setLoading(true); const load=modules[`../docs/${slug}.md`]; if(!load){setMarkdown('# Page not found\n\nChoose a guide from the sidebar.');setLoading(false);return} load().then(m=>{if(active){setMarkdown(m as string);setLoading(false)}}).catch(()=>{if(active){setMarkdown('# Could not load this guide\n\nPlease reload the page.');setLoading(false)}});return()=>{active=false} },[slug])
 return <div className="docs-layout section-wrap"><aside className="docs-sidebar"><a href="#/" className="text-link"><ArrowLeft size={14}/> Back to Cider</a><p className="eyebrow">THE CIDER GUIDE</p><label className="doc-search"><Search size={15}/><input aria-label="Find a guide" placeholder="Find a guide…" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav aria-label="Documentation">{pages.filter(([,name])=>name.toLowerCase().includes(query.toLowerCase())).map(([id,name])=><a key={id} href={`#/docs/${id}`} aria-current={slug===id?'page':undefined}>{name}</a>)}</nav><a className="docs-feedback" href="https://github.com/vatsalsaglani/Cider/issues">Something missing? <ArrowUpRight size={12}/></a></aside><article className="prose" aria-busy={loading}>{loading?<p>Opening your guide…</p>:<ReactMarkdown remarkPlugins={[remarkGfm]} components={{img:({src,alt})=><img src={src?.startsWith('images/')?`${import.meta.env.BASE_URL}${src}`:src} alt={alt||''} loading="lazy"/>,a:({href,children})=><a href={href} {...(href?.startsWith('https:')?{target:'_blank',rel:'noreferrer'}:{})}>{children}</a>}}>{markdown}</ReactMarkdown>}<div className="doc-end">Your next step: <a href="https://github.com/vatsalsaglani/Cider/releases/latest">Get Cider ↗</a></div></article></div>
}
