"""Generate native colors from the same canonical tokens as the design contract."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
tokens = json.loads((root / "design/tokens.json").read_text())
lines = ["// Generated by script/generate_tokens.py. Edit design/tokens.json.", "import SwiftUI", "", "public enum CiderColor {"]
for name, value in tokens["colors"].items():
    channels = [int(value[index:index + 2], 16) / 255 for index in (1, 3, 5)]
    lines.append(f"    public static let {name} = Color(.sRGB, red: {channels[0]:.8f}, green: {channels[1]:.8f}, blue: {channels[2]:.8f}, opacity: 1)")
lines.append("}")
(root / "Sources/CiderUI/Tokens/CiderColor.swift").write_text("\n".join(lines) + "\n")
